services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: kouventahr-be-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kouventahr
    ports:
      - "5432:5432"
    volumes:
      - kouventahr_pgdata:/var/lib/postgresql/data

volumes:
  kouventahr_pgdata: